### ISSUE TITLE
Suggestion: Is it possible to offer the tag number for a type in the exception message ?

### ISSUE THREAD

**Issue by xiaoyuvax** [Cysharp/MemoryPack#105]
I found it is hard to track out the type when exception thrown during serialization/deserialization.
usually a message like below shows, but gives no infomation as which type is wrong (usually due to type registration mismatch between the serializer and the deserializer). 

> Current object's property count is 5 but binary's header maked as 17, can't deserialize about versioning.

I think it would be helpful if the exception message include the pre-registered tag number of the types.

**Comment by neuecc** [comment]
Since the Type on the serialize side does not exist in the data, only the Type on the deserialize side is showable.
Including the Type in the Exception would be nice, however, it would not increase the amount of information itself much, since it would not differ from what can currently be seen from StackTrace.

**Comment by xiaoyuvax** [comment]
StackTrace does not reveal which type registered with MemoryPack is causing the problem( e.g. a type being registered with a different tag number with the deserilizer, i.e. failed version control), especially when deserilizing a complicate type which includes references to multiple other types.

**Comment by neuecc** [comment]
v1.9.8 added type name
