### ISSUE TITLE
Question: CircularReference

### ISSUE THREAD

**Issue by osexpert** [Cysharp/MemoryPack#116]
Hi.
I locked at the code. I notice CircularReference uses an uint (WriteObjectReferenceId). I know that ObjectIDGenerator return long (migrating from BinaryFormatter). So maybe MemoryPack could use ulong too, writing and reading with VarInt would in any case not write any more data than today, but it would support more objects:-) Thou I guess overflowing a uint is very unlikely it seems using a ulong would not hurt? Just a thought:-)

To the real question: I wonder why enabling CircularReference trigger requirement of MemoryPackOrder:
Error	MEMPACK025	The MemoryPackable object 'MethodCall' member 'Arguments' is not annotated MemoryPackOrder

It would be nice if CircularReference could enable without annotating members. And it would be nice if CircularReference could be enabled on the serializer itself, but I guess this is not easy since it is part of the code gen. But...maybe if there was a setting for the code gen where it could be enabled as default, but not sure if this is possible. At least for me I think analyzing all existing classes and figure out if reference tracking is needed (not only for circular but also for references in general, eg. same object in several collections) can be a lot of work for existing code bases.

Last thing: I am confused by this section in the docs:
"By default, annotated [MemoryPackObject] type try to serialize its members. However, if a type is a collection (ICollection<>, ISet<>, IDictionary<,>), use GenerateType.Collection to serialize it correctly."
I tried, and currently there is no compile or runtime error if you do it incorrectly, the collection is just silently missing its content if you do it wrong. This is pretty scary IMO. Can not the code gen detect this and do it correctly, or give a warning?

Thanks!

**Comment by neuecc** [comment]
I don't feel the need to make it ulong, so please tell me when you have a use case that requires it.

CircularReference is an additional version of VersionTolerant.
Therefore, the same restriction applies.
Currently it should be possible to work around it by explicitly specifying `SerializeLayout.Sequential`.

I think if GenerateType should be automatically determined in the case of a Collection.
Since this is one of the initial design errors, I am willing to make the change.
However, it is breaking changes.
