### ISSUE TITLE
Suggestion: support DataContract and DataMember attributes

### ISSUE THREAD

**Issue by afilatov-st** [Cysharp/MemoryPack#188]
We have several classes that are already marked with `[DataContract]` and `[DataMember(Order = x)]` attributes, that we use with protobuf-net (it supports them as alternative to `[ProtoContract]` and  `[ProtoMember]`).
It would be nice if MemoryPack can support them too, that would make the models serializer-independent.

**Comment by neuecc** [comment]
I have no intention of supporting it.
Unlike protobuf-net and MessagePack for C#, you first need to make it partial.
Additionally, the code generated by Source Generate contains MemoryPack code, so unlike other libraries, there is a dependency on the MemoryPack library.
Finally, since there is a need to be conscious of serializing as MemoryPack more than other libraries, I want to make an explicit mark, and when done so, the Analyzer will analyze whether it's properly MemoryPackable or not.
