### ISSUE TITLE
Specific KeyValuePair Unity 2021.3.27f1 and Net7 have different Deserialize results.

### ISSUE THREAD

**Issue by tiarua** [Cysharp/MemoryPack#196]
hello.

I am developing a game using Cysharp libraries.
Thank you very much.

I'm working on a project using Unity 2021.3.27f1 and ASP NET CORE (NET7).

I found one issue.

In Unity 2021.3.27f1, in deserialisation
`int size = Unsafe.SizeOf<KeyValuePair<(int, int, int), int>>();`

In deserialisation in .NET7
`int size = Unsafe.SizeOf<KeyValuePair<(int, int, int), int>>();`

The return values are different in the two functions.

![memorypack](https://github.com/Cysharp/MemoryPack/assets/43740835/8c3f2999-677c-4248-ae22-0b78d3771d4c)

In your project 
Unsafe.SizeOf<KeyValuePair<(enum, enum, int), int>>();
format, but I think this is a similar issue.

I changed the Key to a Class value to resolve the issue, so I don't have the problem anymore.

I am sharing this just in case.

Can the above issue be resolved?
If it can't be solved, and if you have some spare time, I would be really grateful if you could give me some information to study why it can't be solved.

As always, thanks for providing such a great library for game development.

**Comment by neuecc** [comment]
Thanks for check it.
It is caused by breaking change from .NET 7 about `StructLayout.Auto`.
https://github.com/Cysharp/MemoryPack/issues/107#issuecomment-1368190580

ValueTuple is `StructLayout.Auto` so it is prone to compatibility problems.
If you define your own ValueTuple, it will be a SequentialLayout, so you will not have such problems.
