### ISSUE TITLE
BrotliDecompressor take too many CPU

### ISSUE THREAD

**Issue by gruan01** [Cysharp/MemoryPack#210]
Compress & Decompress like the following:
~~~c#
    public RedisValue Serialize<T>(T data)
    {
        using BrotliCompressor compressor = new(CompressionLevel.Optimal);
        MemoryPackSerializer.Serialize(compressor, data);
        return compressor.ToArray();
    }

    public T? Deserialize<T>(RedisValue data)
    {
        var bytes = (byte[]?)data;
        if (bytes == null)
            return default;

        using BrotliDecompressor decompressor = new();
        var buffer = decompressor.Decompress(bytes);
        return MemoryPackSerializer.Deserialize<T>(buffer);
    }
~~~

![CPU Performance](https://github.com/Cysharp/MemoryPack/assets/7332414/adbc4661-7818-4cb6-98ae-70c187a6be4a)

![Data Size](https://github.com/Cysharp/MemoryPack/assets/7332414/28cf9722-fb34-4353-91b7-a0b72381c088)

Is it any way to cache the BrotliDecompressor  instance , or set it to singleton ?

**Comment by neuecc** [comment]
BrotliDecompressor is struct and new() is do nothing.

**Comment by gruan01** [comment]
> BrotliDecompressor is struct and new() is do nothing.

Yes, but method `Decompress` require a instance member `sequenceBuilder`

**Comment by neuecc** [comment]
If you are talking about CPU time, doesn't that mean that the process of decompressing Brotli is taking a long time in the first place?

**Comment by gruan01** [comment]
Maybe, but I'm not sure, it just generated by dotnet-trace.
If `Decompress` not reference instance member `sequenceBuilder`, I can test it by singleton.
But, this method reference instance member, so I can't set `BrotliDecompressor`  to singleton.

**Comment by hadashiA** [comment]
`sequenceBuilder` is object pooled, so it is actually shared.

We would like to clarify a bit what the problem is.

The first screenshot appears to only occupy a percentage.
I would think that when the reusable buffer was first allocated, it would imply that it was a high percentage of the code you executed.
However, I don't know the actual execution time. If the whole thing is a very small percentage, then the percentage does not matter. If it is a small amount of data, then the Deserialize or Decompress itself may have completed in too relatively short a time.

What is meant by the second screenshot?  Is it the sequenceBuilder allocation?
But this is pooled. If the allocation occurs every time, it is a problem, but if so, I don't think it is a problem.

If you still have performance issues, reopen is welcome. Thanks.
