### ISSUE TITLE
Build Error in the script MemoryPackSerializerOptions.cs in MemoryPack.Core 

### ISSUE THREAD

**Issue by fenryo237** [Cysharp/MemoryPack#248]
Hello I am a newbie in MemoryPack and I try to integrate it in ur gaming project to clone object faster than NewtonSoft and for a NativeAOT environment.

I just downloaded the latest release and when I build MemoryPack.Core I have this error message

![image](https://github.com/Cysharp/MemoryPack/assets/159165529/7dffc970-2395-42f6-9641-84865f53859c)

Error	CS1513	} expected	\MemoryPack.Core\MemoryPackSerializerOptions.cs	4	
Error	CS1022	Type or namespace definition, or end-of-file expected	\MemoryPack.Core\MemoryPackSerializerOptions.cs	21	

I really don't see what's missing here.
is there a fix?

EDIT: The installation by Nuggets works fine, but if I want to add the source code to a Nativeaot project it's not building

**Comment by hadashiA** [comment]
The file you have shown ( `\MemoryPack.Core\MemoryPackSerializerOptions.cs` ) does not seem to have any compilation errors.

NOTE:
- MemoryPack.Core also contains C# 12 code.
- I don't know much about your environment, but at least I think it is available from nuget if your goal is .NET Native AOT compilation.

In any case, since 1.20.0 the distribution of packages has been consolidated to nuget, I don't think they will officially support source code distribution.

**Comment by fenryo237** [comment]
Thanks @hadashiA
