### ISSUE TITLE
Native AOT fully compatibility

### ISSUE THREAD

**Issue by hadashiA** [Cysharp/MemoryPack#251]
Building with Native AOT actually works for the most part.
However, it seems that warnings occur because the compiler does not guarantee the operation.

```
/Users/s24061/dev/MemoryPack/src/MemoryPack.Core/bin/Release/net8.0/MemoryPack.Core.dll : warning IL2104: Assembly 'MemoryPack.Core' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries [/Users/s24061/dev/MemoryPack/sandbox/SandboxConsoleApp/SandboxConsoleApp.csproj]
/Users/s24061/dev/MemoryPack/src/MemoryPack.Core/bin/Release/net8.0/MemoryPack.Core.dll : warning IL3053: Assembly 'MemoryPack.Core' produced AOT analysis warnings. [/Users/s24061/dev/MemoryPack/sandbox/SandboxConsoleApp/SandboxConsoleApp.csproj]
```

If we add `<IsAotCompatible>true</IsAotCompatible>` to MemoryPack.Core.csproj,  will see many warnings of the following types:
- IL2072
- IL2090
- IL2091
- IL3050

To fix this, it may be necessary to change to a mechanism that does not use reflection.

**Comment by TechInterMezzo** [comment]
So, is this off the table?

**Comment by W1zzardTPU** [comment]
> So, is this off the table?

Indeed .. looks like the project is mostly abandoned... and it looked so promising :( Have you found any comparable solution that works well with AOT?

**Comment by dusrdev** [comment]
@W1zzardTPU The actual trimming can be somewhat fixed by manually registering the formatters, like so:

```csharp
MemoryPackFormatterProvider.Register<T>(); // where T is the type you are trying to serialize
```

I managed to get this to work by calling this static method somewhere that is guaranteed to be executed before any serialization/deserialization for that type is used.

* There are also similar methods in the same static class for collections and dictionaries.

While this solved trimming in all of my tests (functionally, everything worked even with AOT), the compiler warnings are still produced. I would still caution against using this in a full production environment where stability is a priority—unless tested very rigorously.

# Alternatives - My Suggestions

If are looking for a simple way just to serialize/deserialize to binary (bytes), I would look no further than the build-in `System.Text.Json` which starting from .NET 9 (or the 9.0.0 version of the standalone nuget package) has the API's for `SerializeToUtf8Bytes`. They are extremely well-optimized, very stable and perfectly AOT compatible with a source generated `JsonSerializerContext`

If, however you're looking for a complete (yet still simple) framework for key-value storage, I've built my own based on `System.Text.Json`'s new APIs - [ArrowDb](https://github.com/dusrdev/ArrowDb)

**Comment by W1zzardTPU** [comment]
> can be somewhat fixed by manually registering the formatters

Indeed, I discovered that last week, which is another "wontfix" issue .. #270 

> They are extremely well-optimized, very stable and perfectly AOT compatible with a source generated `JsonSerializerContext`

Great tip, will test

**Comment by W1zzardTPU** [comment]
and 20 minutes later, it's working perfectly using JsonSerializer.

Polymorphism support is identical to MemoryPack, the only gotcha I came across is that serializing IntPtr isn't supported, just declare as Int64 instead.

Some quick and dirty non-scientific performance testing:

MemoryPack:
```
Request: Prepare data took 0.0120 ms
Request: Invoke took 0.0441 ms
Request: Decode took 0.0110 ms
Refresh 1.7475 ms
Request: Prepare data took 0.0106 ms
Request: Invoke took 0.0438 ms
Request: Decode took 0.0118 ms
Refresh 1.0925 ms
Request: Prepare data took 0.0122 ms
Request: Invoke took 0.0474 ms
Request: Decode took 0.0125 ms
Refresh 1.4441 ms
Request: Prepare data took 0.0114 ms
Request: Invoke took 0.0530 ms
Request: Decode took 0.0123 ms
Refresh 1.1087 ms
```

SerializeToUtf8Bytes with JsonSerializerContext:
```
Request: Prepare data took 0.0635 ms
Request: Invoke took 0.2857 ms
Request: Decode took 0.1522 ms
Refresh 1.7172 ms
Request: Prepare data took 0.0438 ms
Request: Invoke took 0.7077 ms
Request: Decode took 0.0491 ms
Refresh 1.8273 ms
Request: Prepare data took 0.0408 ms
Request: Invoke took 0.1217 ms
Request: Decode took 0.0619 ms
Refresh 1.6316 ms
Request: Prepare data took 0.0394 ms
Request: Invoke took 0.0943 ms
Request: Decode took 0.0435 ms
Refresh 1.5903 ms
```

That's definitely fast enough and a cost that I'd happily take for a fully supported approach without external dependencies

**Comment by dusrdev** [comment]
@W1zzardTPU Looks great. Just make sure that if you are serializing to and from files, when you write them, reset the file (i.e start the new serialization on a fresh file), otherwise there could be issues with overlap, and JSON tokens don't handle that well.

**Comment by W1zzardTPU** [comment]
> files

Running in-memory, think IPC/RPC
