### ISSUE TITLE
Guidance for migrating from MessagePack to MemoryPack

### ISSUE THREAD

**Issue by bitbonk** [Cysharp/MemoryPack#259]
Is there some guidance somewhere how to migrate from MessagePack to MemoryPack? 
What are the functional differences and what features of MessagePack do not work in MemoryPack anymore?

**Comment by hadashiA** [comment]
No automatic migrating, etc. is provided, so please look at the respective documentation to make your decision.

If you are using MessagePack-CSharp, you probably only need to change the attribute in your type definition, since the APIs are similar.
If you are just communicating from C# type to C# type, the functionality may not be much different.

The major difference is the binary format.
MessagePack can dump data only as a primitive array or DIctionary, like JSON, and can also use other language parsers to convert to JSON.
However, MemoryPack has a limitation that it cannot parse without a C# type definition. This restriction is similar to that of protobufs.
Due to format differences, MemoryPack also does not support deserialization to dynamic types.

Also, the current MessagePack-CSharp does not seem to have a Source Generator, but it is planned for the next major version.
