### ISSUE TITLE
Unity support

### ISSUE THREAD

**Issue by c0nd3v** [Cysharp/MemoryPack#4]
I’m curious if supporting a lower version is possible? If we target C# 9/.NET Standard 2.1/Roslyn 3.9.0 we can support Unity. @neuecc I know you already know all of this, I’m just curious what features from C# 11/.NET 7 are required. Thanks.

**Comment by hez2010** [comment]
It's C# 11/.NET 7 specific, because it's extensively using ref fields, abstract static methods in interface which are only available in .NET 7+. The mono runtime as well as il2cpp ships with Unity simply doesn't support those features at all.

**Comment by neuecc** [comment]
C# 11/ .NET 7 will not be available in Unity for a long time (Unity 2025?).
In order to run it in Unity today, it would require dedicated code that replaced it extensively (a slight decrease in performance, but I think the decrease would be less significant).
After the current .NET 7 is used to users and the code is more reliable, I may think about it.

**Comment by neuecc** [comment]
I've released `1.4.0`, it supports it.
