### ISSUE TITLE
Bug: failed System.TypeLoadException

### ISSUE THREAD

**Issue by mirbeta** [Cysharp/MemoryPack#54]
The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted. System.TypeLoadException: Virtual static method 'Serialize' is not implemented on type 'SystemModule.Packets.ServerPackets.ServerDataMessage' from assembly 'SystemModule, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by neuecc** [comment]
please provide more details and reproduce code?

**Comment by neuecc** [comment]
Thank you.
I've understand issue.
NetStandard 2.1 class library can not use from Net7 application.
This is because the .NET 7 version uses static abstract members that require runtime updates.
You need to update library to Net7(or use TargetFrameworks netstandard2.1;net7.0).

This will be noted in the ReadMe, as the error is not easy to understand.
Thanks.

**Comment by neuecc** [comment]
Library developer, configure dual target framework.
`<TargetFrameworks>netstandard2.1;net7.0</TargetFrameworks>`
Applicatoin developer, only to use net7.0.
`<TargetFramework>net7.0</TargetFramework>`

**Comment by NicoIer** [comment]
> Library developer, configure dual target framework. `<TargetFrameworks>netstandard2.1;net7.0</TargetFrameworks>` Applicatoin developer, only to use net7.0. `<TargetFramework>net7.0</TargetFramework>`

It works !

**Comment by NicoIer** [comment]
@neuecc Another issue is that when I want to use some code in the unity client and .net8 server, the data uploaded by the client is parsed by the server in a way that doesn't match the original data

**Comment by NicoIer** [comment]
https://github.com/Cysharp/MemoryPack/blob/main/src/MemoryPack.UnityShims/Shims.cs
When the server uses Vector3 in Shim and the Unity client uses UnityEngine.Vector3, the value of the Vector3 uploaded by the client is not parsed correctly on the server side, is this the correct behavior, because UnityEngine.Vector3 is really not tagged in Unity as [ MemoryPackable]
